name: User Service CI

on:
  push:
    branches:
      - main
      - Dev_branch
    
  pull_request:
    branches:
      - main
      - Dev_branch
    
permissions:
  contents: write
  packages: write
  

jobs:
  ci:
    name: "User Service Pipeline"
    uses: Harshitha3826/Reusable-template/.github/workflows/ci-template.yml@main
    with:
      working_directory: "."
      image_name: "user-service"
      service-name: "user-service"
      run_build: false
      sonar_project_key: "user-service"
      docker_context: "."
      dockerfile_path: "Dockerfile"
      helm_repo: "Harshitha3826/Vastra-helm"
      helm_chart_path: "vastra-deployments"
      values_file: "values-dev.yaml"
      helm_service_key: "Vastra-user-service"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      HELM_REPO_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
